# Generated by Django 5.2.12 on 2026-03-30 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('mudiri', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boshqaradigan_kafedralar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kafedralar',
            },
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fanlar', to='app.kafedra')),
            ],
            options={
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='Oqituvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familiya', models.CharField(max_length=100)),
                ('lavozim', models.CharField(choices=[('professor', 'Professor'), ('dotsent', 'Dotsent'), ('katta_oqituvchi', "Katta o'qituvchi"), ('oqituvchi', "O'qituvchi"), ('assistant', 'Assistant'), ('stajyor', 'Stajyor')], default='oqituvchi', max_length=20)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='oqituvchilar/')),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ilmiy_daraja', models.CharField(blank=True, max_length=100)),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oqituvchilar', to='app.kafedra')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "O'qituvchilar",
            },
        ),
        migrations.CreateModel(
            name='Dars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(choices=[('maruza', "Ma'ruza"), ('amaliyot', 'Amaliyot'), ('laboratoriya', 'Laboratoriya'), ('seminar', 'Seminar')], max_length=20)),
                ('xona', models.CharField(blank=True, max_length=20)),
                ('boshlanish_vaqti', models.TimeField()),
                ('tugash_vaqti', models.TimeField()),
                ('hafta_kuni', models.IntegerField(choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba')])),
                ('semestr', models.IntegerField(default=1)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='darslar', to='app.fan')),
                ('oqituvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='darslar', to='app.oqituvchi')),
            ],
            options={
                'verbose_name_plural': 'Darslar',
            },
        ),
        migrations.CreateModel(
            name='OylikStatistika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oy', models.DateField()),
                ('umumiy_yuklama', models.FloatField(default=0)),
                ('bajarilgan', models.FloatField(default=0)),
                ('bajarilgan_foiz', models.FloatField(default=0)),
                ('kafedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistikalar', to='app.kafedra')),
            ],
            options={
                'verbose_name_plural': 'Oylik statistikalar',
                'ordering': ['-oy'],
            },
        ),
        migrations.CreateModel(
            name='Reyting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.FloatField(default=0)),
                ('oy', models.DateField()),
                ('talaba_baho', models.FloatField(default=0)),
                ('izoh', models.TextField(blank=True)),
                ('oqituvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reytinglar', to='app.oqituvchi')),
            ],
            options={
                'verbose_name_plural': 'Reytinglar',
                'ordering': ['-oy'],
            },
        ),
        migrations.CreateModel(
            name='Yuklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oquv_yili', models.CharField(max_length=20)),
                ('maruza_soat', models.FloatField(default=0)),
                ('amaliyot_soat', models.FloatField(default=0)),
                ('laboratoriya_soat', models.FloatField(default=0)),
                ('jami_soat', models.FloatField(default=0)),
                ('bajarilgan_foiz', models.FloatField(default=0)),
                ('oqituvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yuklamalar', to='app.oqituvchi')),
            ],
            options={
                'verbose_name_plural': 'Yuklamalar',
            },
        ),
    ]
