# Generated by Django 5.2.12 on 2026-04-28 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oqituvchi',
            name='stavka',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='oqituvchi',
            name='stavka_turi',
            field=models.CharField(choices=[('asosiy', 'Asosiy'), ('orindosh', "O'rindosh"), ('soatbay', 'Soatbay')], default='asosiy', max_length=20),
        ),
        migrations.CreateModel(
            name='FanYuklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oquv_yili', models.CharField(default='2024-2025', max_length=20)),
                ('semestr', models.IntegerField(default=1)),
                ('fan_nomi', models.CharField(max_length=200)),
                ('yonalish', models.CharField(blank=True, max_length=50)),
                ('fakultet', models.CharField(blank=True, max_length=50)),
                ('kredit', models.IntegerField(default=0)),
                ('kurs', models.IntegerField(default=1)),
                ('talabalar_soni', models.IntegerField(default=0)),
                ('potok_soni', models.IntegerField(default=0)),
                ('guruh_soni', models.IntegerField(default=0)),
                ('kichik_guruh', models.IntegerField(default=0)),
                ('maruza_reja', models.FloatField(default=0)),
                ('maruza_jami', models.FloatField(default=0)),
                ('amaliyot_reja', models.FloatField(default=0)),
                ('amaliyot_jami', models.FloatField(default=0)),
                ('laboratoriya_reja', models.FloatField(default=0)),
                ('laboratoriya_jami', models.FloatField(default=0)),
                ('seminar_reja', models.FloatField(default=0)),
                ('seminar_jami', models.FloatField(default=0)),
                ('reyting_1ob_turi', models.CharField(blank=True, max_length=10)),
                ('reyting_1ob_soati', models.FloatField(default=0)),
                ('reyting_ob_turi', models.CharField(blank=True, max_length=10)),
                ('reyting_ob_soati', models.FloatField(default=0)),
                ('reyting_yb_turi', models.CharField(blank=True, max_length=10)),
                ('reyting_yb_soati', models.FloatField(default=0)),
                ('kurs_ishi', models.FloatField(default=0)),
                ('kurs_loyihasi', models.FloatField(default=0)),
                ('magistr_dissertatsiya', models.FloatField(default=0)),
                ('bmi', models.FloatField(default=0)),
                ('rahbarlik', models.FloatField(default=0)),
                ('amaliyot_soati', models.FloatField(default=0)),
                ('dak', models.FloatField(default=0)),
                ('ilmiy_nazariy', models.FloatField(default=0)),
                ('izoh', models.CharField(blank=True, max_length=200)),
                ('jami', models.FloatField(default=0)),
                ('oqituvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_yuklamalari', to='app.oqituvchi')),
            ],
            options={
                'verbose_name_plural': 'Fan yuklamalari',
                'ordering': ['oqituvchi', 'semestr', 'fan_nomi'],
            },
        ),
    ]
