# Generated by Django 5.2.12 on 2026-05-09 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_seed_shokirov'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='kredit',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('yonalish', models.CharField(blank=True, max_length=100)),
                ('kurs', models.IntegerField(default=1)),
                ('talabalar_soni', models.IntegerField(default=0)),
                ('kafedra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guruhlar', to='app.kafedra')),
            ],
            options={
                'verbose_name_plural': 'Guruhlar',
            },
        ),
        migrations.AddField(
            model_name='dars',
            name='guruh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='darslar', to='app.guruh'),
        ),
    ]
