# Generated by Django 5.2.12 on 2026-05-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_fan_kredit_guruh_dars_guruh'),
    ]

    operations = [
        migrations.AddField(
            model_name='dars',
            name='bajarildi',
            field=models.BooleanField(default=False),
        ),
    ]
